### ISSUE TITLE
Edit Dev Guide, API Reference, and Release Notes

### ISSUE THREAD

**Issue by cyrichardson** [rackerlabs/docs-cloud-load-balancers#103]
(Getting Started Guide already edited).

**Comment by kmsholcomb** [comment]
I'm on it!

**Comment by cyrichardson** [comment]
Just moving things to here so that the Waffle board shows them. @kmsholcomb Thanks!

**Comment by kmsholcomb** [comment]
Hi @cyrichardson: I finished editing the rest of the API content. I've attached the Word doc with the markup and a PDF copy of the Word doc. Please let me know if you have any questions or have any feedback for me. Thanks!

[Rackspace Cloud Load Balancers API 2_editsKH.pdf](https://github.com/rackerlabs/docs-cloud-load-balancers/files/151406/Rackspace.Cloud.Load.Balancers.API.2_editsKH.pdf)
[Rackspace Cloud Load Balancers API 2_editsKH.docx](https://github.com/rackerlabs/docs-cloud-load-balancers/files/151407/Rackspace.Cloud.Load.Balancers.API.2_editsKH.docx)

**Comment by cyrichardson** [comment]
@kmsholcomb Thanks a ton!!!

**Comment by cyrichardson** [comment]
@kmsholcomb Guess this issue can be closed (for waffle board) for your work and I'll apply the edits via Issue #104
