### ISSUE TITLE
Apply Kelly's edits to Dev Guide, API Reference, and Release Notes

### ISSUE THREAD

**Issue by cyrichardson** [rackerlabs/docs-cloud-load-balancers#104]

**Comment by meker12** [comment]
Closed with PR #102

**Comment by cyrichardson** [comment]
PR #102 only applied edits to the Getting Started Guide. Kelly is still working on the rest of the doc. There is another open issue for that editing.

**Comment by cyrichardson** [comment]
See issue #103  for Kelly's edits.
