### ISSUE TITLE
Remove _build output from v1 and v2 directories

### ISSUE THREAD

**Issue by meker12** [rackerlabs/docs-cloud-load-balancers#105]
Also, to avoid merge conflicts and lots of new files checked in every time.

Update .gitignore specification: 

_build/*   >>  api-docs/_build/*

**Comment by cyrichardson** [comment]
@meker12 Thanks! Is that the exact code I need to add to my gitignore file? 

_build/* >> api-docs/_build/*

I've been trying to fix that but didn't get it right. So thanks for this!

**Comment by cyrichardson** [comment]
PR #110
