### ISSUE TITLE
Update contributor collateral

### ISSUE THREAD

**Issue by meker12** [rackerlabs/docs-cloud-load-balancers#114]
Kelly edited the contributor collateral, and we added a CONTRIBUTING.md so that users get the link to contributor instructions when working in the repo.

Using [Cloud Identity](https://github.com/rackerlabs/docs-cloud-identity] as a model, update the info for contributors:

 - [x] Revise README.md
 - [x] Add CONTRIBUTING.md
 - [x] Add GITHUBING.md

Update all links and naming to match product.

**Comment by cyrichardson** [comment]
Completed via PRs #122 and #123
