### ISSUE TITLE
Feedback on LB v1 prototype for refactored API docs

### ISSUE THREAD

**Issue by meker12** [rackerlabs/docs-cloud-load-balancers#138]
We'd appreciate your review and feedback on the API Guide prototype to refactor the content architecture and navigation for the Public Cloud API documentation. 

- Click through navigation
- Check chunking of information by using Prev and Next links
- Check H1 topics for local contents

Provide any feedback or suggestions for improvement in this issue by Friday, June 17

Thanks for your help!

This issue is a child of the [IA - WS issue #58](https://github.com/rackerlabs/docs-workstream/issues/58).
See that issue for additional information.

**Comment by cyrichardson** [comment]
@meker12 @kmsholcomb 
- The navigation on the left looks fantastic! Such a great improvement over current design. 
- I checked the Prev and Next links and have no suggestions for any changes to them. I know some of the "chunks" are large, but I think what you have works.
- H1 topics look good to me!
You've done a wonderful job and provide a great improvement to our docs!

**Comment by kallimachos** [comment]
Looks good to me. I think any chunking adjustments at this point can be handled through document IA.

I have one nit about the location of the ``Submit an issue`` link, but that is a general thing so I've raised an issue here: https://github.com/rackerlabs/docs-rackspace/issues/106.

**Comment by meker12** [comment]
@catlook  Any feedback on the new API guide architecture?

**Comment by meker12** [comment]
Review complete - See [IA - WS issue #58](https://github.com/rackerlabs/docs-workstream/issues/58). for next steps
