### ISSUE TITLE
inaccurate documentation to add node to load balancer

### ISSUE THREAD

**Issue by joeashcraft** [rackerlabs/docs-cloud-load-balancers#152]
### Report an issue with the documentation

Document with the issue: https://github.com/rackerlabs/docs-cloud-load-balancers/blob/master/api-docs/cloud-load-balancers-v1/api-reference/methods/post-add-node-v1.0-account-loadbalancers-loadbalancerid-nodes.rst

**Report incorrect information:**
This document states that to add a node to a load balancer, 

> this operation does not accept a request body.

**This is incorrect; the operation *requires* a request body** and the very next section in the docs have an example request body.

**Comment by joeashcraft** [comment]
In my testing, I found 3 required fields and 1 option field to **add a node**.

Required: address, port, condition
Optional: type, weight

**Comment by cyrichardson** [comment]
@joeashcraft Thanks for reporting this! I'll get this fix today.

**Comment by cyrichardson** [comment]
See PR #155
#155 (comment)

**Comment by cyrichardson** [comment]
Closed with PR #155
