### ISSUE TITLE
Broken links in common section getting-started/send-request-ovw/#send-api-requests

### ISSUE THREAD

**Issue by cyrichardson** [rackerlabs/docs-cloud-load-balancers#153]
Below is Nick's email. I found several broken links in this common section.
*************************************************************************************

From: Rackspace Hosting <catherine.richardson@RACKSPACE.COM>
Date: Tuesday, July 5, 2016 at 11:55 AM
To: Nicholas Kuechler <nicholas.kuechler@rackspace.com>, Jesse Noller <jesse.noller@rackspace.com>
Cc: Laura Clymer <laura.clymer@rackspace.com>, group-laura-clymer <group-laura-clymer@rackspace.com>
Subject: Re: bad link in developer docs

Thanks, Nick! I’ll check this out and get it fixed.

- Catherine

From: Nicholas Kuechler <nicholas.kuechler@rackspace.com>
Date: Tuesday, July 5, 2016 at 11:09 AM
To: Jesse Noller <jesse.noller@rackspace.com>
Cc: Laura Clymer <laura.clymer@rackspace.com>, group-laura-clymer <group-laura-clymer@rackspace.com>
Subject: Re: bad link in developer docs

Ah, didn't notice that link.

Thanks!

-Nick

On Jul 5, 2016, at 11:07 AM, Jesse Noller <jesse.noller@RACKSPACE.COM> wrote:

That would be Laura’s Info dev team under me! CC’ing them

Also note the ‘file an issue’ link in the upper left: https://github.com/rackerlabs/docs-cloud-load-balancers/issues - bugs go straight to the team

On Jul 5, 2016, at 11:03 AM, Nicholas Kuechler <nicholas.kuechler@rackspace.com> wrote:

Hey Jesse,

A customer in freenode #rackspace channel noticed a bad link in this section:

https://developer.rackspace.com/docs/cloud-load-balancers/v1/getting-started/send-request-ovw/#send-api-requests

In the first blue box, the 'try using Rackspace SDKs' link is a dead link.

I'm not sure what team owns the developer docs page but I knew you're involved in a lot of the developer-related stuff, so I was hoping you could forward this to the docs folks.

Cheers,
Nick

**Comment by kmsholcomb** [comment]
@cyrichardson @meker12: I am editing the new template for the API guides, so I will check all the links, too, and ensure they are correct and up-to-date.

**Comment by cyrichardson** [comment]
Thanks, @kmsholcomb! I'm off to create a PR for this change in the common stuff and Cat's has offered to review it.

**Comment by kmsholcomb** [comment]
Hi @cyrichardson. I am actually fixing it in the common content (in docs-common), so you don't need to do it. If you want to create an issue for fixing it, I'll close the issue when it is done.

**Comment by cyrichardson** [comment]
@kmsholcomb OK! Thanks for fixing it!
@catlook ^^ so don't look for PR from me to review/merge!

**Comment by cyrichardson** [comment]
@kmsholcomb - Here's the issue for docs-common - https://github.com/rackerlabs/docs-common/issues/58
