### ISSUE TITLE
update-node requires a request body

### ISSUE THREAD

**Issue by joeashcraft** [rackerlabs/docs-cloud-load-balancers#156]
**Two Parts!**

1. "modify nodes" vs "update node"
2. update-node request body

## Link to Documentation with Issue
[cloud-load-balancers#update-node](https://developer.rackspace.com/docs/cloud-load-balancers/v1/api-reference/nodes/#update-node
)

## Editorial or Format Problem
This paragraph in the header uses different terminology than the rest of the doc.

> At least one of the optional attributes is required for the **Modify Nodes** request. (emphasis mine)

"Modify Nodes" appears only once; Update Node appears 4 times. **I propose** changing the single instance of "modify nodes" to read "update node".

## Missing Information
'update-node' does require a request body. The header mentions this, but the 'update-node' section states that the "operation does not accept a request body." This is similar to #152 (fixed with #155). Maybe we copy/paste the same table which lists optional and required attributes/parameters.

**Comment by cyrichardson** [comment]
See PR #155 
https://github.com/rackerlabs/docs-cloud-load-balancers/pull/155#issuecomment-230618987
