### ISSUE TITLE
Needs an explanation of what happens when connections are throttled

### ISSUE THREAD

**Issue by inflatador** [rackerlabs/docs-cloud-load-balancers#189]
### Report an issue with the documentation

Describe your documentation issue in  the relevant section. Submit product operation or 
performance issues to the Rackspace product team at https://feedback.rackspace.com/.

**Link to documentation with issue:**  
https://developer.rackspace.com/docs/cloud-load-balancers/v1/api-reference/throttle-connections/

**Report missing information:**
Per https://one.rackspace.com/x/1Y5oGg , the Cloud Load Balancer will return a 503 Server Too Busy if it is throttling connections. However, we don't have that anywhere in the docs, and customers assume there's something wrong with the CLB when they see a 503 error.

If we could get the information in the one wiki article into the CLB docs, that would help clear things up for customers.

**Comment by cyrichardson** [comment]
Thanks, @inflatador! We'll work on getting this doc update to you for review this week.
