### ISSUE TITLE
Loadbalancer SSL documentation

### ISSUE THREAD

**Issue by phantomadam** [rackerlabs/docs-cloud-load-balancers#192]
When updating an SSL certificate on SSL Termination the private key field is named "privatekey" whereas when updating an SSL on Certificate Mapping it is instead "privateKey" ( note the capital K on key ). The API seems to be case sensitive and report a 400 error. Is it either possible to update the API to make is not case sensitive or update the documentation to make this clear?

Thanks

Adam

**Comment by cyrichardson** [comment]
Hi, @phantomadam. Thanks for the information and opening this issue. I'm on the Information Development team and we can certainly update the doc. Which does not give the 400 error - privatekey or privateKey? 

(I'm not sure that there is any active development on Cloud Load Balancers at this time.)

**Comment by phantomadam** [comment]
Both supply the 400 error, it's just that SSL Termination expects 'privatekey' and Certificate Mapping expects 'privateKey'. Maybe just a note on the docs which says "Please note case as it differs between termination and mapping" ( just so another dev doesn't spend 3 hours banging their head against the screen trying to work out why it's not working lol )

**Comment by cyrichardson** [comment]
Thanks so much, @phantomadam! Your idea of a note sounds perfect. I'll ask for your review on the PR when I get it created.
