### ISSUE TITLE
CLB Cipher Profile Table Missing Bullets

### ISSUE THREAD

**Issue by LukeRepko** [rackerlabs/docs-cloud-load-balancers#296]
### Report an issue with the documentation

Describe your documentation issue in the relevant section.

**Link to documentation with issue:** 
https://docs.rackspace.com/docs/cloud-load-balancers/v1/api-reference/ciphers/  
https://github.com/rackerlabs/docs-cloud-load-balancers/blame/master/api-docs/cloud-load-balancers-v1/api-reference/ciphers.rst#L44-L62 

**Report editorial or format problem:** 

**Report incorrect information:**

**Report missing information:**
Table bullets are missing in FireFox and Chrome.

**Documentation feedback:**

**Comment by dereknoblej** [comment]
This has been resolved.

**Comment by LukeRepko** [comment]
Closing as it's resolved.
