### ISSUE TITLE
Edits for migrated release notes

### ISSUE THREAD

**Issue by kmsholcomb** [rackerlabs/docs-cloud-load-balancers#66]
The attached Word doc has my suggested edits for the migrated release notes. Please let me know if you have any questions. Thanks!

[Cloud Load Balancers Release Notes_editsKH.docx](https://github.com/rackerlabs/docs-cloud-load-balancers/files/29243/Cloud.Load.Balancers.Release.Notes_editsKH.docx)

**Comment by masthalter** [comment]
I implemented your edits and published the Release Notes.

Thanks!

Mike
