### ISSUE TITLE
GSG QE: Add link about annotated service catalog

### ISSUE THREAD

**Issue by cyrichardson** [rackerlabs/docs-cloud-load-balancers#71]
In Authentication section, above the Example: Authentication response add the following: 

.. note:: 
     For detailed information about the authentication response, see the 
     :rax-devdocs:`annotated authentication request and response<cloud-identity/v2/developer-guide/#document-authentication-info/sample-auth-req-response>` in the Rackspace Cloud API documentation.

**Comment by masthalter** [comment]
Fixed.

Thanks Catherine!

Mike
