### ISSUE TITLE
Folder structure for Sphinx projects

### ISSUE THREAD

**Issue by meker12** [rackerlabs/docs-cloud-load-balancers#76]
For the API Sphinx docs, we're standardizing on a folder structure like this:

├── api-docs
│   ├── Makefile
│   ├── _build
│   │   └── deconst-single
│   ├── _deconst.json
│   ├── api-operations
│   │   ├── access-lists.rst
│   │   ├── algorithms.rst
│   │   ├── allowed-domains.rst

Load balancers has the Sphinx source project three levels down: 

├── rst
│   └── dev-guide
│       ├── common-gs
│       │   ├── auth-using-curl.rst
│       │   ├── get-credentials.rst
│       │   ├── how-to-use-curl.rst
│       │   ├── images
│       │   │   └── show-api-key-control-panel.png
│       │   ├── samples
│       │   │   ├── auth-req-curl.rst
│       │   │   ├── auth-resp-json.rst
│       │   │   ├── auth-token-object.rst
│       │   │   └── service-catalog-endpoint.rst
│       │   └── using-env-variables.rst
│       ├── getting-started
│       │   ├── authenticate.rst
│       │   ├── examples
│       │   │   ├── add-node.rst
│       │   │   ├── copy-paste-curl-terminal.rst
│       │   │   ├── create-cloud-servers-to-lb.rst
│       │   │   ├── create-load-balancer.r

This might be accounting for the fact that LB still has internal doc book content in the src directory.  

When that content is converted, we should adjust the directory to match the other API doc source repos.

**Comment by cyrichardson** [comment]
Fixed
