### ISSUE TITLE
Docs project updates

### ISSUE THREAD

**Issue by meker12** [rackerlabs/docs-cloud-load-balancers#80]
- [x] Add disclaimer to Developer Docs [Trello card] (https://trello.com/c/mC8WjS05)

- [x] Update _deconst.json to add variables to enable **Edit on GitHub** feature [Trello card](https://trello.com/c/U7m8RsvU)

- [x] Remove SLA and pricing topic from docs [Trello card](https://trello.com/c/lzxa1vx2/3206-remove-sla-and-pricing-from-devdocs)

**Comment by cyrichardson** [comment]
2nd and 3rd items above fixed by Margaret's PRs #84, #81, #87, #83, and #82

**Comment by cyrichardson** [comment]
1st item taken care of in a PR that is coming, hopefully, by EOD Monday, 2/6/2016, with other updates to Dev Guide and Release Notes for Release v1.25.26.

**Comment by cyrichardson** [comment]
1st item closed by PR #89
