### ISSUE TITLE
Work to publish v2 EA docs externally to developer.rackspace.com

### ISSUE THREAD

**Issue by meker12** [rackerlabs/docs-cloud-load-balancers#94]
Build and deploy v2 docs.
- [x]  Enable build
  Update cibuild script to add v2 docs to Travis build. (Merge PR #93).
- [x]  Configure DRC deployment
  Update nexus control configuration to [add content repo](https://github.com/rackerlabs/nexus-control/blob/master/config/content.d/developer.rackspace.com.json) and [routes](https://github.com/rackerlabs/nexus-control/blob/master/config/routes.d/developer.rackspace.com.json)  (Submit PR or [request help](https://github.com/rackerlabs/nexus-control/issues/new) ).
- [x] Add deliverables to landing page
  Update [docs-landing page](https://github.com/rackerlabs/docs-quickstart/edit/master/index.rst) (Submit PR or [request help](https://github.com/rackerlabs/docs-quickstart/issues/new))

**Comment by cyrichardson** [comment]
Latest roadmap show CLB v2 EA launch in June 2016.

**Comment by cyrichardson** [comment]
From: Trent Gillaspie <trent.gillaspie@RACKSPACE.COM>
Date: Wednesday, June 15, 2016 at 1:17 PM
To: Rackspace Hosting <catherine.richardson@RACKSPACE.COM>, Carrie Brady <carrie.brady@rackspace.com>
Cc: Jorge Miramontes <jorge.miramontes@RACKSPACE.COM>
Subject: Re: Any new news? Re: Do you want v1 and v2 CLB API docs available at the same time on developer.rackspace.com?

Hi Catherine,

Thank you for reaching out. As of now, the CLB v2.0 EA launch date is set for 7/12. I will make a note to keep you in the loop for your needs from a documentation perspective. Please let me know if you need anything further.

Thanks,
Trent

Trent Gillaspie

Rackspace | Product Manager | 303.386.6115

Strategic | Futuristic | Communication | Responsibility | Arranger

/////////////////////////////////////////////////////

From: Catherine Richardson <catherine.richardson@RACKSPACE.COM>
Date: Wednesday, June 15, 2016 at 10:26 AM
To: Trent Gillaspie <trent.gillaspie@rackspace.com>, Carrie Brady <carrie.brady@rackspace.com>
Cc: Catherine Richardson <catherine.richardson@RACKSPACE.COM>
Subject: FW: Any new news? Re: Do you want v1 and v2 CLB API docs available at the same time on developer.rackspace.com?

Hi, Trent and Carrie,

I got Jorge’s OOO email so I’m forwarding this to you.

Any news on CLB v2 EA launch date?

Thanks,
Catherine

**Comment by cyrichardson** [comment]
On 7/12/16, 10:00 AM, "Jorge Miramontes" <jorge.miramontes@RACKSPACE.COM>
wrote:

Hey Catherine,

More delays :(. We are still working through a few things but it's
looking like we are delayed for at least a week. I'll keep you informed.

--Jorge

On Jul 11, 2016, at 3:40 PM, Catherine Richardson
<catherine.richardson@RACKSPACE.COM> wrote:
Hi, Jorge,
Just checking to make sure the launch is still on for tomorrow.
Will you please let me know via email when you are ready for me to
publish to docs?
Thanks!
-Catherine

**Comment by cyrichardson** [comment]
Closing this PR without merging because CLBv2 has been cancelled.
